### ISSUE TITLE
Possible Mod Support

### ISSUE THREAD

**Issue by ryu777mtg** [phantamanta44/cloche-plus-plus#2]
Have been using the mod for awhile not sure if you are taking on any suggestions but I think a few things that would help with this mod.

Possibly add support for Mysical Creations that mod allows users to add custom seeds, cruxs, etc. very easily however they will not grow in the Cloche

If the above is not able to be accomplished what about adding a config option to be able to add user created components sorta like how you have the options in the config to remove them, using the same format I think this could be accomplished.

Thanks for your time and hope this could be accomplished

**Comment by phantamanta44** [comment]
it seems like mystical creations is already supposed to have built-in garden cloche support: https://github.com/Focamacho/MysticalCreations/issues/7
